---
- name: reload systemd
  command: systemctl daemon-reload
  sudo: yes

- name: restart etcd
  service: name=etcd.service state=started enabled=yes
  sudo: yes

- name: restart flannel
  service: name=flannel.service state=restarted enabled=yes
  sudo: yes

- name: restart docker
  service: name=docker.service state=restarted enabled=yes
  sudo: yes

- name: restart kube-apiserver
  service: name=kube-apiserver.service state=restarted enabled=yes
  sudo: yes

- name: restart kube-controller-manager
  service: name=kube-controller-manager.service state=restarted enabled=yes
  sudo: yes

- name: restart kube-kubelet
  service: name=kube-kubelet.service state=restarted enabled=yes
  sudo: yes

- name: restart kube-proxy
  service: name=kube-proxy.service state=restarted enabled=yes
  sudo: yes

- name: restart kube-scheduler
  service: name=kube-scheduler.service state=restarted enabled=yes
  sudo: yes
