---
- name: Create /opt/bin for custom binaries
  sudo: yes
  file: >
    path=/opt/bin
    state=directory
    owner=core
    group=core

# INSTALL FLANNEL BINARY

- name: Check if flannel is installed
  stat: path="/opt/bin/flanneld"
  register: flannel_binary

- name: Clone flannel repository
  git: >
    dest={{ flannel_repository_path }}
    repo=https://github.com/coreos/flannel.git
    version=master
  when: not flannel_binary.stat.exists

- name: Build flannel through docker container
  command: >
    docker run -v {{ flannel_repository_path }}:/opt/flannel
    -i -t google/golang /bin/bash -c "cd /opt/flannel && ./build"
  when: not flannel_binary.stat.exists

- name: Move built binary to correct place
  sudo: yes
  command: >
    mv {{ flannel_repository_path }}/bin/flanneld /opt/bin/flanneld
    creates="/opt/bin/flanneld"
  when: not flannel_binary.stat.exists

# INSTALL KUBERNETES BINARIES

- name: Check if kubernetes binaries are installed
  stat: path="/opt/bin/kubecfg"
  register: kubernetes_binary

- name: Clone kubernetes coreos repository
  git: >
    dest={{ kubernetes_coreos_repository_path }}
    repo=https://github.com/jussil/kubernetes-coreos.git
    version=master
  when: not kubernetes_binary.stat.exists

- name: Build kubernetes binaries through docker container
  command: >
    docker build --no-cache -t kelseyhightower/kubernetes-binaries:latest
    {{ kubernetes_coreos_repository_path }}
  when: not kubernetes_binary.stat.exists

- name: Run built container and copy binaries
  command: >
    docker run -v /opt/bin:/b kelseyhightower/kubernetes-binaries:latest
    /bin/bash -c "cp /kubernetes-binaries/* /b"
  when: not kubernetes_binary.stat.exists

# ENABLE COMMON SYSTEMD SERVICES

- name: Configure docker.service
  template: src=docker.service 
            dest=/etc/systemd/system/docker.service
            owner=root
            group=root
            mode=0644
  sudo: yes
  notify: restart docker
