---
# Common tasks for every node
- include: common.yml

# Kubernetes master specific tasks
- include: master.yml
  when: "'master' in group_names"

# Kubernetes minion specific tasks
- include: minion.yml
  when: "'minions' in group_names"
